version: '3'

services:
  web:
    build: athermosillo/myapp_web:prod
    ports:
      - "80:3000"
    env_file:
      - .env/production/web
      - .env/production/database

  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data

  db-migrator:
    image: athermosillo/myapp_web:prod
    command: ["./wait-for", "--timeout=300", "database:5432", "--", "bin/rails", "db:migrate"]
    env_file:
      - .env/production/web
      - .env/production/database
    deploy:
      restart_policy:
        condition: none
    
volumes:
  db_data:
